# Generated by Django 5.1 on 2026-03-02 16:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('ordered', 'Sent to Supplier'), ('partial', 'Partially Received'), ('received', 'Fully Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('receipt_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.warehouse')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchasing.purchaseorder')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='Approval level (1, 2, 3...)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_approvals', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='purchasing.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Approval',
                'verbose_name_plural': 'Purchase Order Approvals',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='core.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'verbose_name': 'Purchase Order Line',
                'verbose_name_plural': 'Purchase Order Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_lines', to='inventory.lot')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='purchasing.purchaseorderline')),
            ],
            options={
                'verbose_name': 'Goods Receipt Line',
                'verbose_name_plural': 'Goods Receipt Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('requested_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('required_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to PO')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='company.company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchasing.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('unit_price_estimate', models.DecimalField(decimal_places=2, default=0, help_text='Estimated unit price', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisition_lines', to='core.item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaserequisition')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'verbose_name': 'Purchase Requisition Line',
                'verbose_name_plural': 'Purchase Requisition Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID/VAT Number')),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, help_text='Mobile phone for urgent contact', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('payment_terms_days', models.PositiveIntegerField(default=30, help_text='Payment terms in days')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_terms_days', models.PositiveIntegerField(default=30, help_text='Credit terms in days')),
                ('currency', models.CharField(default='ETB', help_text='Transaction currency', max_length=3)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=20)),
                ('performance_rating', models.DecimalField(decimal_places=2, default=0, help_text='Supplier performance rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of on-time deliveries', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_rating', models.DecimalField(decimal_places=2, default=0, help_text='Quality rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier status')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier'),
        ),
        migrations.CreateModel(
            name='VendorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('on_time_deliveries', models.PositiveIntegerField(default=0)),
                ('late_deliveries', models.PositiveIntegerField(default=0)),
                ('damaged_orders', models.PositiveIntegerField(default=0)),
                ('total_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='purchasing.supplier')),
            ],
            options={
                'verbose_name': 'Vendor Performance',
                'verbose_name_plural': 'Vendor Performance Records',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['receipt_number'], name='purchasing__receipt_ee1bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['po', 'receipt_date'], name='purchasing__po_id_d47f84_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderapproval',
            index=models.Index(fields=['status', 'level'], name='purchasing__status_eec5c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderapproval',
            unique_together={('po', 'level')},
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requisition_number'], name='purchasing__requisi_92bc36_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['status', 'requested_date'], name='purchasing__status_8d029d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['code'], name='purchasing__code_2994d5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tin'], name='purchasing__tin_6df57b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active', 'is_preferred'], name='purchasing__is_acti_14034f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['performance_rating'], name='purchasing__perform_ad721d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchasing__po_numb_f09ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchasing__status_04b4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchasing__order_d_09a604_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchasing__supplie_dddc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorperformance',
            index=models.Index(fields=['supplier', 'period_start'], name='purchasing__supplie_56ab0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorperformance',
            unique_together={('supplier', 'period_start', 'period_end')},
        ),
    ]
