# Generated by Django 5.1 on 2026-03-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='purchaseorderapproval',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='vendorperformance',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
    ]
