# Generated by Django 5.1 on 2026-03-02 16:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='e.g. WHO compliant recipe v2.3 - March 2026')),
                ('base_quantity', models.DecimalField(decimal_places=4, default=1.0, help_text='BOM is defined per this many kg of product (usually 1)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(limit_choices_to={'category': 'finished'}, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='core.item')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_kg', models.DecimalField(decimal_places=6, help_text='Kg / Meters / Pcs per 1 kg of finished product', max_digits=12, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('wastage_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard wastage % from your BOM table', max_digits=5)),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.bom')),
                ('component', models.ForeignKey(limit_choices_to={'category__in': ['raw', 'packing']}, on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'verbose_name': 'BOM Line',
                'verbose_name_plural': 'BOM Lines',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, help_text="Planned production quantity (in product's unit, usually kg)", max_digits=15, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Planned Qty')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Actual produced quantity (filled on completion)', max_digits=15, null=True, verbose_name='Actual Qty')),
                ('waste_quantity', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Quantity of waste/scrap generated', max_digits=15, null=True, verbose_name='Waste Qty')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='planned', max_length=20)),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When production was started / planned')),
                ('end_date', models.DateTimeField(blank=True, help_text='When production was completed or cancelled', null=True)),
                ('notes', models.TextField(blank=True)),
                ('estimated_material_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated material cost at planning time', max_digits=15, null=True)),
                ('standard_material_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Standard material cost from BOM', max_digits=15, null=True)),
                ('actual_material_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual material cost from consumption', max_digits=15, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Labor cost for this run', max_digits=15, null=True)),
                ('overhead_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Overhead cost for this run', max_digits=15, null=True)),
                ('material_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Material cost variance (actual - standard)', max_digits=15, null=True)),
                ('total_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost variance', max_digits=15, null=True)),
                ('yield_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Production yield percentage', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='production.bom', verbose_name='Bill of Materials')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'category': 'finished'}, on_delete=django.db.models.deletion.PROTECT, related_name='produced_runs', to='core.item', verbose_name='Finished Product')),
            ],
            options={
                'verbose_name': 'Production Run',
                'verbose_name_plural': 'Production Runs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCostVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('standard_material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Standard Material Cost')),
                ('actual_material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Actual Material Cost')),
                ('material_variance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Material Variance')),
                ('standard_labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Standard Labor Cost')),
                ('actual_labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Actual Labor Cost')),
                ('labor_variance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Labor Variance')),
                ('standard_overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Standard Overhead Cost')),
                ('actual_overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Actual Overhead Cost')),
                ('overhead_variance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Overhead Variance')),
                ('standard_total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Standard Total Cost')),
                ('actual_total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Actual Total Cost')),
                ('total_variance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Total Variance')),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Variance %')),
                ('item_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed variance per component', verbose_name='Item Breakdown')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('production_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_variance', to='production.productionrun', verbose_name='Production Run')),
            ],
            options={
                'verbose_name': 'Production Cost Variance',
                'verbose_name_plural': 'Production Cost Variances',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Positive = added to stock, Negative = removed from stock', max_digits=15)),
                ('movement_type', models.CharField(choices=[('in_purchase', 'Received from Purchase'), ('in_production', 'Produced (Finished Goods)'), ('out_production', 'Consumed in Production'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment_add', 'Manual Add – Adjustment'), ('adjustment_remove', 'Manual Remove – Adjustment'), ('return', 'Return from Customer'), ('return_supplier', 'Return to Supplier'), ('scrap', 'Scrap / Waste'), ('sample', 'Quality Sample')], db_index=True, max_length=30, verbose_name='Movement Type')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Reference')),
                ('notes', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=4, help_text='Stock balance before this movement', max_digits=15, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=4, help_text='Stock balance after this movement', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.warehouse', verbose_name='From Warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.item', verbose_name='Item')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.warehouse', verbose_name='To Warehouse')),
                ('production_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='production.productionrun', verbose_name='Production Run')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product', 'is_active'], name='production__product_e0e709_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['effective_from'], name='production__effecti_347b74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='bomline',
            unique_together={('bom', 'component')},
        ),
        migrations.AddIndex(
            model_name='productionrun',
            index=models.Index(fields=['status', 'start_date'], name='production__status_d93fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrun',
            index=models.Index(fields=['product', 'status'], name='production__product_47c80b_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostvariance',
            index=models.Index(fields=['production_run'], name='production__product_7a79e8_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostvariance',
            index=models.Index(fields=['calculated_at'], name='production__calcula_a66960_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='production__movemen_a6b8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', 'created_at'], name='production__item_id_4f7117_idx'),
        ),
    ]
