# Generated by Django 5.1 on 2026-03-05 16:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['product', 'bom_type', '-version'], 'verbose_name': 'Bill of Materials', 'verbose_name_plural': 'Bills of Materials'},
        ),
        migrations.AlterModelOptions(
            name='bomline',
            options={'ordering': ['bom', 'sequence', 'id'], 'verbose_name': 'BOM Line', 'verbose_name_plural': 'BOM Lines'},
        ),
        migrations.RemoveIndex(
            model_name='bom',
            name='production__product_e0e709_idx',
        ),
        migrations.RemoveIndex(
            model_name='bom',
            name='production__effecti_347b74_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='quantity_per_kg',
        ),
        migrations.AddField(
            model_name='bom',
            name='base_uom',
            field=models.ForeignKey(default=1, help_text='Unit of measure for base quantity (usually Kg)', on_delete=django.db.models.deletion.PROTECT, related_name='bom_base_uoms', to='core.unit'),
        ),
        migrations.AddField(
            model_name='bom',
            name='bom_type',
            field=models.CharField(choices=[('formula', 'Formula / Recipe'), ('packing', 'Packing Materials')], default='formula', max_length=20),
        ),
        migrations.AddField(
            model_name='bom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bom',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Leave blank if currently active', null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default BOM for this product type'),
        ),
        migrations.AddField(
            model_name='bom',
            name='yield_percent',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Expected yield percentage (usually 100%)', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bomline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomline',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Critical component that must be in stock'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='quantity_per_base',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Quantity needed for the base quantity (usually 1000 kg of finished product)', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=1000.0, help_text='BOM is defined per this many kg of product (1000 kg = 1 Metric Ton)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='component',
            field=models.ForeignKey(limit_choices_to={'category__in': ['raw', 'packing']}, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='core.item'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=10, help_text='Order in the BOM (10,20,30...)'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_line_units', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='wastage_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard wastage % from your BOM table', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'bom_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product', 'bom_type', 'is_active'], name='production__product_23ca3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['effective_from', 'effective_to'], name='production__effecti_1b2424_idx'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom', 'component'], name='production__bom_id_afb672_idx'),
        ),
    ]
