# Generated by Django 5.1 on 2026-03-05 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0002_alter_bom_options_alter_bomline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=1000.0, help_text='Base quantity (usually 1000kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bom',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_base_units', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='notes',
            field=models.TextField(blank=True, help_text='Example: WHO compliant recipe v2.3'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='yield_percent',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Expected yield %', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='quantity_per_base',
            field=models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=10, help_text='10,20,30 order'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='wastage_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
