# Generated by Django 5.1 on 2026-03-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('production', '0003_alter_bom_base_quantity_alter_bom_base_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='productioncostvariance',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company'),
        ),
    ]
