# Generated by Django 5.1 on 2026-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_bom_company_bomline_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, help_text='Planned completion datetime', null=True),
        ),
    ]
