# Generated by Django 5.1 on 2026-03-10 08:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionrun_planned_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Unique batch number for the finished lot.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1000.0000'), help_text='Base quantity (1000 kg)', max_digits=10),
        ),
    ]
