# Generated by Django 5.1 on 2026-03-05 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0003_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='salespayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesshipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesshipmentline',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='salesinvoice',
            name='sales_sales_invoice_b577c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinvoice',
            name='sales_sales_status_54d75f_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinvoice',
            name='sales_sales_custome_0d19f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_sales_order_n_78c57a_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_sales_status_fc0419_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_sales_custome_23226b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='salesshipmentline',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='sales_order_line',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='std_composition_pct',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='std_consumption_per_mt',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='std_wastage_pct',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='actual_ship_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='expected_ship_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='invoice_generated',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='quantity_invoiced',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='quantity_shipped',
        ),
        migrations.RemoveField(
            model_name='salespayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salespayment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='salespayment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.customer'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('invoiced', 'Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile', 'Mobile Money'), ('check', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='shipment_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesshipmentline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesshipmentline',
            name='sales_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderline'),
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='notes',
        ),
    ]
