# Generated by Django 5.1 on 2026-03-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('sales', '0002_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={},
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salespayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesshipment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='quantity_shipped',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile', 'Mobile'), ('check', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesshipmentline',
            name='sales_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='sales.salesorderline'),
        ),
    ]
