# Generated by Django 5.1 on 2026-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='fs_number',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Credit'), ('cash', 'Cash')], default='credit', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
