# Generated by Django 5.1 on 2026-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_fs_number_salesinvoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
