# Generated by Django 5.1 on 2026-03-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_salesorder_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-invoice_date', '-id'], 'verbose_name': 'Sales Invoice', 'verbose_name_plural': 'Sales Invoices'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceline',
            options={'ordering': ['id'], 'verbose_name': 'Sales Invoice Line', 'verbose_name_plural': 'Sales Invoice Lines'},
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='discount_percent',
        ),
    ]
