# Generated by Django 5.0.1 on 2024-03-10 15:00

from django.db import migrations


def recalculate_totals(apps, schema_editor):
    """
    Iterate through all Sales Orders and Invoices and recalculate their totals
    to fix any inconsistencies from previous logic.
    """
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    SalesInvoice = apps.get_model('sales', 'SalesInvoice')
    
    print("\nRecalculating Sales Order totals...")
    orders = SalesOrder.objects.all()
    for i, order in enumerate(orders):
        if (i + 1) % 50 == 0:
            print(f"  - Processed {i + 1}/{orders.count()} orders...")
        order.calculate_totals()
    print(f"  - Done. Processed {orders.count()} orders.")

    print("\nRecalculating Sales Invoice totals...")
    invoices = SalesInvoice.objects.all()
    for i, invoice in enumerate(invoices):
        if (i + 1) % 50 == 0:
            print(f"  - Processed {i + 1}/{invoices.count()} invoices...")
        invoice.calculate_totals()
    print(f"  - Done. Processed {invoices.count()} invoices.")


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(recalculate_totals, migrations.RunPython.noop),
    ]