# Generated by Django 5.1 on 2026-03-05 14:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this unit is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['abbreviation'], name='core_unit_abbrevi_fa2ad4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique item code', max_length=50, unique=True)),
                ('peach_code', models.CharField(blank=True, max_length=100, verbose_name='Peach / Purchase Name')),
                ('name', models.CharField(help_text='Item name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('category', models.CharField(choices=[('raw', 'Raw Material'), ('semi', 'Semi-Finished'), ('finished', 'Finished Product'), ('packing', 'Packing Material'), ('consumable', 'Consumable'), ('asset', 'Fixed Asset')], db_index=True, max_length=20)),
                ('product_type', models.CharField(blank=True, choices=[('plumpy_nut', "Plumpy'Nut"), ('plumpy_sup', "Plumpy'Sup"), ('other', 'Other')], max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_purchased', models.BooleanField(default=True, help_text='Can this item be purchased?')),
                ('is_sold', models.BooleanField(default=False, help_text='Can this item be sold?')),
                ('is_stocked', models.BooleanField(default=True, help_text='Is this item stocked in inventory?')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='730 for 24 months', null=True)),
                ('min_shelf_life_on_receipt', models.PositiveIntegerField(default=180, help_text='Minimum remaining shelf life when received (days)')),
                ('allergen_peanut', models.BooleanField(default=False, help_text='Contains peanut allergen')),
                ('pack_size_kg', models.DecimalField(blank=True, decimal_places=4, help_text="e.g. 0.092 for Plumpy'Nut sachet", max_digits=8, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Item weight in kg', max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=4, help_text='Item volume in cubic meters', max_digits=10, null=True)),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO - First In First Out'), ('lifo', 'LIFO - Last In First Out'), ('average', 'Weighted Average'), ('standard', 'Standard Cost')], default='average', help_text='Method used for stock valuation', max_length=20)),
                ('std_unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard / budgeted unit price (for variance analysis)', max_digits=12, verbose_name='Standard Unit Price')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cost per unit (per kg, per piece, etc.) - last purchase or average cost', max_digits=12, verbose_name='Unit Cost')),
                ('current_avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, help_text='Weighted average cost from purchases', max_digits=12, verbose_name='Average Cost')),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text="Current quantity in stock (in the item's base unit)", max_digits=15, verbose_name='Current Stock')),
                ('minimum_stock', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Alert when stock falls below this level (safety stock)', max_digits=12, verbose_name='Minimum Stock Level')),
                ('maximum_stock', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Maximum desired stock level', max_digits=12, verbose_name='Maximum Stock Level')),
                ('reorder_point', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='When stock reaches this level, trigger reorder (should be >= minimum_stock)', max_digits=12, verbose_name='Reorder Point')),
                ('reorder_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Suggested quantity to order when below reorder point', max_digits=12, verbose_name='Reorder Quantity')),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Typical lead time in days for procurement')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='VAT/Tax rate percentage', max_digits=5)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System code for customs', max_length=20, verbose_name='HS Code')),
                ('default_location', models.CharField(blank=True, help_text='Default storage location in warehouse', max_length=100)),
                ('bin_location', models.CharField(blank=True, help_text='Bin/shelf location', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.unit')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='core_item_code_2c57e9_idx'), models.Index(fields=['category'], name='core_item_categor_206c33_idx'), models.Index(fields=['is_active'], name='core_item_is_acti_8c2f25_idx'), models.Index(fields=['product_type'], name='core_item_product_46c56f_idx'), models.Index(fields=['current_stock', 'minimum_stock'], name='core_item_current_4d51f4_idx')],
            },
        ),
    ]
