# Generated by Django 5.1 on 2026-03-09 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0003_delete_currency_item_company_unit_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('manufacturing', 'Manufacturing'), ('admin', 'Administration')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
            options={
                'ordering': ['module', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['company', 'module', 'action'], name='core_permis_company_0c4964_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('company', 'module', 'action')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['company', 'name'], name='core_role_company_7b42e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='core_rolepe_role_id_777955_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['company', 'user', 'role'], name='core_userro_company_b3b9c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('company', 'user', 'role')},
        ),
    ]
