# Generated by Django 5.1 on 2026-03-02 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_payments', to='purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bill', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_bills', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_bills', to='purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.purchasebill'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='core.item'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='core.unit'),
        ),
        migrations.AddField(
            model_name='reconciliationauditlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounting.payment'),
        ),
        migrations.AddField(
            model_name='reconciliationauditlog',
            name='reconciled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_c93a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='accounting__account_8b352f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_date'], name='accounting__company_4bb435_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted', 'entry_date'], name='accounting__is_post_6951f8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'journal'], name='accounting__account_72d578_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'date'], name='accounting__payment_f525a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='accounting__custome_0f2c50_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['supplier'], name='accounting__supplie_0ccb96_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['bill_number'], name='accounting__bill_nu_302026_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['status'], name='accounting__status_3d4a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['due_date'], name='accounting__due_dat_021795_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['supplier', 'bill_date'], name='accounting__supplie_46920c_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationauditlog',
            index=models.Index(fields=['reconciled_at'], name='accounting__reconci_05ec19_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationauditlog',
            index=models.Index(fields=['action'], name='accounting__action_0891f4_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationauditlog',
            index=models.Index(fields=['payment'], name='accounting__payment_1b6448_idx'),
        ),
    ]
