# Generated by Django 5.1 on 2026-03-13 20:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_fiscalperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target budget amount', max_digits=15),
        ),
    ]
