# Generated by Django 5.1 on 2026-03-02 16:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Goods Receipt (Purchase)'), ('issue', 'Issue to Production'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Warehouse Transfer'), ('return', 'Return from Production'), ('return_supplier', 'Return to Supplier'), ('scrap', 'Scrap / Waste'), ('sample', 'Quality Sample')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost at time of transaction', max_digits=12, null=True)),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='GRN-001, PO-001, PROD-20260226-003, etc.', max_length=100)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='RM-STORE, FG-WH, etc.', max_length=20, unique=True)),
                ('warehouse_type', models.CharField(choices=[('raw', 'Raw Materials'), ('packing', 'Packing Materials'), ('finished', 'Finished Goods'), ('wip', 'Work in Progress'), ('quarantine', 'Quarantine'), ('damaged', 'Damaged Goods'), ('returns', 'Returns'), ('consignment', 'Consignment')], default='raw', help_text='Type of warehouse', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, default='Addis Ababa', max_length=100)),
                ('country', models.CharField(blank=True, default='Ethiopia', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager', models.CharField(blank=True, help_text='Warehouse manager name', max_length=100)),
                ('capacity', models.DecimalField(blank=True, decimal_places=4, help_text='Total capacity in cubic meters or kg', max_digits=12, null=True)),
                ('capacity_unit', models.CharField(default='m³', help_text='Unit of capacity measurement', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_damaged', models.BooleanField(default=False, help_text='Is this a damaged goods warehouse?')),
                ('is_quarantine', models.BooleanField(default=False, help_text='Is this a quarantine warehouse?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity reserved for production/sales', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock', to='core.item')),
            ],
            options={
                'verbose_name': 'Current Stock',
                'verbose_name_plural': 'Current Stock',
                'ordering': ['item__code', 'warehouse__name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='PN-20260226-001', max_length=50, unique=True)),
                ('supplier_batch', models.CharField(blank=True, help_text="Supplier's batch number", max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('initial_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocated_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity allocated to production orders', max_digits=12)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quarantine', 'In Quarantine')], default='pending', max_length=20)),
                ('quality_checked_date', models.DateTimeField(blank=True, null=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('certificate_of_analysis', models.FileField(blank=True, help_text='Certificate of Analysis', null=True, upload_to='lots/coa/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False, help_text='Blocked from use')),
                ('block_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lots', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.item')),
                ('quality_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot/Batch',
                'verbose_name_plural': 'Lots/Batches',
                'ordering': ['-expiry_date', 'batch_number'],
            },
        ),
    ]
