# Generated by Django 5.1 on 2026-03-02 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='currentstock',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stocktransaction'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='currentstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_stock', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['batch_number'], name='inventory_l_batch_n_daf847_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['expiry_date'], name='inventory_l_expiry__232401_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['quality_status'], name='inventory_l_quality_7fcfcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('item', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type'], name='inventory_w_warehou_b51245_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='inventory_s_transac_23e651_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference'], name='inventory_s_referen_19fe6a_idx'),
        ),
        migrations.AddIndex(
            model_name='currentstock',
            index=models.Index(fields=['item', 'warehouse'], name='inventory_c_item_id_646747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currentstock',
            unique_together={('item', 'warehouse', 'lot')},
        ),
    ]
