# Generated by Django 5.1 on 2026-03-09 19:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0004_permission_role_rolepermission_userrole_and_more'),
        ('inventory', '0004_currentstock_company_lot_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=50)),
                ('document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_in', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('quantity_out', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('balance_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posting_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='core.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['posting_date', 'id'],
                'indexes': [models.Index(fields=['company', 'product', 'warehouse'], name='inventory_s_company_394f5b_idx'), models.Index(fields=['document_type', 'document_id'], name='inventory_s_documen_b81455_idx'), models.Index(fields=['posting_date'], name='inventory_s_posting_1b823f_idx')],
            },
        ),
    ]
