# Generated by Django 5.1 on 2026-03-02 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('inventory_stock_summary', 'Stock Summary'), ('inventory_stock_value', 'Stock Value'), ('inventory_stock_aging', 'Stock Aging'), ('inventory_low_stock', 'Low Stock Alert'), ('inventory_expiry', 'Expiry Report'), ('inventory_movements', 'Stock Movements'), ('inventory_reorder', 'Reorder Analysis'), ('production_runs', 'Production Runs'), ('production_cost_variance', 'Cost Variance'), ('production_yield', 'Production Yield'), ('production_efficiency', 'Production Efficiency'), ('production_material_consumption', 'Material Consumption'), ('production_downtime', 'Downtime Analysis'), ('purchasing_po_summary', 'Purchase Order Summary'), ('purchasing_supplier_performance', 'Supplier Performance'), ('purchasing_spend_analysis', 'Spend Analysis'), ('purchasing_lead_time', 'Lead Time Analysis'), ('purchasing_price_trend', 'Price Trend'), ('sales_order_summary', 'Sales Order Summary'), ('sales_invoice_summary', 'Sales Invoice Summary'), ('sales_customer_performance', 'Customer Performance'), ('sales_revenue_analysis', 'Revenue Analysis'), ('sales_product_sales', 'Product Sales'), ('sales_forecast', 'Sales Forecast'), ('financial_profit_loss', 'Profit & Loss'), ('financial_balance_sheet', 'Balance Sheet'), ('financial_cash_flow', 'Cash Flow'), ('financial_trial_balance', 'Trial Balance'), ('financial_accounts_receivable', 'Accounts Receivable Aging'), ('financial_accounts_payable', 'Accounts Payable Aging'), ('financial_budget_variance', 'Budget vs Actual'), ('company_customer_list', 'Customer List'), ('company_supplier_list', 'Supplier List'), ('company_user_activity', 'User Activity'), ('custom_sql', 'Custom SQL Report'), ('custom_aggregate', 'Custom Aggregate')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('template_file', models.CharField(blank=True, help_text='Path to custom template', max_length=255)),
                ('query_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for report query')),
                ('icon', models.CharField(blank=True, default='bi-file-earmark-text', max_length=50)),
                ('color', models.CharField(blank=True, default='primary', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reportcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, default=1, help_text='0=Monday, 6=Sunday', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('time', models.TimeField(default='08:00')),
                ('recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_tables', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('kpi', 'KPI Card'), ('list', 'List'), ('calendar', 'Calendar'), ('custom', 'Custom HTML')], max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('full', 'Full Width')], default='medium', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
